### ISSUE TITLE
[AES-GCM] Maintaining nonce value between sealing and opening

### ISSUE THREAD

**Issue by jplock** [ctz/hpke-py#5]
I'm implementing an application to encrypt data and then decrypt it later on (using AES-GCM-128). For each encrypted data element, I'm storing the encrypted ciphertext and the AAD value, but I think I also need to persist the nonce value. How can I get access to that?

https://github.com/ctz/hpke-py/blob/main/hpke/hpke.py#L239-L245

**Comment by ctz** [comment]
You don't need to persist either the AAD (ever!) or nonce (in the case of HPKE).

**Comment by jplock** [comment]
In my case, I'm trying to use AWS KMS to generate my keys. I'm able to get a private plaintext key out of KMS, but then do I need to wrap it somehow to reflect the same `nonce` values as sealing?

The situation I'm running into is, I have a Dict of Python keys and encrypted values. I'm iterating over the Dict and am able to decrypt the first value. Every other value fails decryption with `InvalidTag`, so I feel like something with the nonce values are getting out of sync but I can't track it down to where.

```python
plaintext_secret_key: bytes = self.kms.decrypt(encrypted_secret_key)
sk: ec.EllipticCurvePrivateKey = serialization.load_der_private_key(plaintext_secret_key, password=None)
```

The `sk` value is able to be used in `suite.open()`

```python
plaintext: bytes = self.suite.open(
            encap=data.encapped_key,
            our_privatekey=sk,
            info=info,
            aad=aad,
            ciphertext=data.ciphertext,
        )
```

on the first iteration but fails on every other iteration

**Comment by ctz** [comment]
> on the first iteration but fails on every other iteration

sorry, iteration of what? `self.suite.open` is a one-shot API so it doesn't really make sense to call it in a loop

the earlier link is not a one-shot API, so you can call it for successive messages and the nonce sequence is implicit in the order of the messages.

see https://www.rfc-editor.org/rfc/rfc9180.html#name-message-order-and-message-l

**Comment by jplock** [comment]
Thank you for that link. Using the single shot APIs is what I need to do.
